---
- name: Deploying using Ansible
  hosts: anurag_pc
  become: true

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Pull latest Docker image 
      shell: docker pull anurag9507/scientific-calculator:1.0

    - name: Remove old container if exists
      shell: docker rm -f scientific-calculator
      ignore_errors: true

    - name: Run Calculator container in detached mode
      shell: docker run -dit --name scientific-calculator anurag9507/scientific-calculator:1.0

    - name: Show running containers
      shell: docker ps
      register: docker_ps

    - name: Print running container info
      debug:
        var: docker_ps.stdout