---
- name: Deploying using Ansible
  hosts: anurag_pc
  become: true

  vars:
    image_name: "anurag9507/scientific-calculator:latest"
    container_name: "scientific-calculator"

  tasks:
    - name: 0. Ensure Docker is installed
      ansible.builtin.pip:
        name: docker
        state: present

    - name: 1. Pull latest Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: 2. Remove any old container if it exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: 3. Run calculator in detached mode
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        detach: yes 
        interactive: yes
        tty: yes
        recreate: true